# Generated by Django 6.0 on 2026-01-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_cliente_id_alter_detallepedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Ventas/img'),
        ),
    ]
